;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Cooldown.Attack",DevComment="")
+GameplayTagList=(Tag="Cooldown.Block",DevComment="")
+GameplayTagList=(Tag="Cooldown.Dash",DevComment="")
+GameplayTagList=(Tag="Data.Cooldown",DevComment="")
+GameplayTagList=(Tag="Data.Damage",DevComment="")
+GameplayTagList=(Tag="Data.Heal",DevComment="")
+GameplayTagList=(Tag="Event.Abilities.Changed",DevComment="")
+GameplayTagList=(Tag="Event.ActivateAbility.Dash",DevComment="")
+GameplayTagList=(Tag="Event.ActivateAbility.Parry",DevComment="")
+GameplayTagList=(Tag="Event.Enemy.TargetUpdated",DevComment="")
+GameplayTagList=(Tag="Event.HitScan.End",DevComment="")
+GameplayTagList=(Tag="Event.HitScan.Start",DevComment="")
+GameplayTagList=(Tag="Event.Projectile.Explode",DevComment="")
+GameplayTagList=(Tag="Event.SpawnProjectile",DevComment="")
+GameplayTagList=(Tag="Event.Weapon.Equip",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Enemy.Attack",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Movement.Dash",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Projectile",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Weapon.Axe.Attack",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Weapon.Axe.Block",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Weapon.Equip",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Weapon.Parry",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Weapon.Staff.Attack",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Damage.Blocked",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Damage.Burst",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Dash.Activate",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Heal.Burst",DevComment="")
+GameplayTagList=(Tag="GameplayCue.SpikeLaunch.Activate",DevComment="")
+GameplayTagList=(Tag="Status.Block",DevComment="")
+GameplayTagList=(Tag="Status.Dead",DevComment="")
+GameplayTagList=(Tag="Status.Objective.Capturing",DevComment="")
+GameplayTagList=(Tag="Status.Stamina.Regen",DevComment="")
+GameplayTagList=(Tag="Weapon.Melee.Axe",DevComment="")
+GameplayTagList=(Tag="Weapon.Ranged.Staff",DevComment="")

